/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProfileRecipeIndexRouteImport } from './routes/profile/recipe/index'
import { Route as ProfileSick_leaveMyRouteImport } from './routes/profile/sick_leave/my'
import { Route as ProfileArrangedReceptionDashboardRouteImport } from './routes/profile/arranged-reception/dashboard'
import { Route as ProfileArrangedReceptionCreateRouteImport } from './routes/profile/arranged-reception/create'
import { Route as ProfileReceptionIdCreateRouteImport } from './routes/profile/reception/$id.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRecipeIndexRoute = ProfileRecipeIndexRouteImport.update({
  id: '/profile/recipe/',
  path: '/profile/recipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSick_leaveMyRoute = ProfileSick_leaveMyRouteImport.update({
  id: '/profile/sick_leave/my',
  path: '/profile/sick_leave/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileArrangedReceptionDashboardRoute =
  ProfileArrangedReceptionDashboardRouteImport.update({
    id: '/profile/arranged-reception/dashboard',
    path: '/profile/arranged-reception/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileArrangedReceptionCreateRoute =
  ProfileArrangedReceptionCreateRouteImport.update({
    id: '/profile/arranged-reception/create',
    path: '/profile/arranged-reception/create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileReceptionIdCreateRoute =
  ProfileReceptionIdCreateRouteImport.update({
    id: '/profile/reception/$id/create',
    path: '/profile/reception/$id/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/profile/arranged-reception/create': typeof ProfileArrangedReceptionCreateRoute
  '/profile/arranged-reception/dashboard': typeof ProfileArrangedReceptionDashboardRoute
  '/profile/sick_leave/my': typeof ProfileSick_leaveMyRoute
  '/profile/recipe': typeof ProfileRecipeIndexRoute
  '/profile/reception/$id/create': typeof ProfileReceptionIdCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/profile/arranged-reception/create': typeof ProfileArrangedReceptionCreateRoute
  '/profile/arranged-reception/dashboard': typeof ProfileArrangedReceptionDashboardRoute
  '/profile/sick_leave/my': typeof ProfileSick_leaveMyRoute
  '/profile/recipe': typeof ProfileRecipeIndexRoute
  '/profile/reception/$id/create': typeof ProfileReceptionIdCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/profile/arranged-reception/create': typeof ProfileArrangedReceptionCreateRoute
  '/profile/arranged-reception/dashboard': typeof ProfileArrangedReceptionDashboardRoute
  '/profile/sick_leave/my': typeof ProfileSick_leaveMyRoute
  '/profile/recipe/': typeof ProfileRecipeIndexRoute
  '/profile/reception/$id/create': typeof ProfileReceptionIdCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/profile/arranged-reception/create'
    | '/profile/arranged-reception/dashboard'
    | '/profile/sick_leave/my'
    | '/profile/recipe'
    | '/profile/reception/$id/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/profile/arranged-reception/create'
    | '/profile/arranged-reception/dashboard'
    | '/profile/sick_leave/my'
    | '/profile/recipe'
    | '/profile/reception/$id/create'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/profile/arranged-reception/create'
    | '/profile/arranged-reception/dashboard'
    | '/profile/sick_leave/my'
    | '/profile/recipe/'
    | '/profile/reception/$id/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ProfileArrangedReceptionCreateRoute: typeof ProfileArrangedReceptionCreateRoute
  ProfileArrangedReceptionDashboardRoute: typeof ProfileArrangedReceptionDashboardRoute
  ProfileSick_leaveMyRoute: typeof ProfileSick_leaveMyRoute
  ProfileRecipeIndexRoute: typeof ProfileRecipeIndexRoute
  ProfileReceptionIdCreateRoute: typeof ProfileReceptionIdCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/recipe/': {
      id: '/profile/recipe/'
      path: '/profile/recipe'
      fullPath: '/profile/recipe'
      preLoaderRoute: typeof ProfileRecipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/sick_leave/my': {
      id: '/profile/sick_leave/my'
      path: '/profile/sick_leave/my'
      fullPath: '/profile/sick_leave/my'
      preLoaderRoute: typeof ProfileSick_leaveMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/arranged-reception/dashboard': {
      id: '/profile/arranged-reception/dashboard'
      path: '/profile/arranged-reception/dashboard'
      fullPath: '/profile/arranged-reception/dashboard'
      preLoaderRoute: typeof ProfileArrangedReceptionDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/arranged-reception/create': {
      id: '/profile/arranged-reception/create'
      path: '/profile/arranged-reception/create'
      fullPath: '/profile/arranged-reception/create'
      preLoaderRoute: typeof ProfileArrangedReceptionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reception/$id/create': {
      id: '/profile/reception/$id/create'
      path: '/profile/reception/$id/create'
      fullPath: '/profile/reception/$id/create'
      preLoaderRoute: typeof ProfileReceptionIdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  ProfileArrangedReceptionCreateRoute: ProfileArrangedReceptionCreateRoute,
  ProfileArrangedReceptionDashboardRoute:
    ProfileArrangedReceptionDashboardRoute,
  ProfileSick_leaveMyRoute: ProfileSick_leaveMyRoute,
  ProfileRecipeIndexRoute: ProfileRecipeIndexRoute,
  ProfileReceptionIdCreateRoute: ProfileReceptionIdCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
